project:
  type: website
  output-dir: _site

website:
  title: "UCT Mathematics Society"
  favicon: logo.png
  site-url: https://zentannen.github.io/mathsoc/
  navbar:
    logo: logo.png
    logo-alt: "UCT Mathematics Society"
    background: "#002145"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Events"
        href: events.qmd
      - text: "Competitions"
        menu:
          - text: "Mathathon"
            href: mathathon.qmd
          - text: "Integration Bee"
            href: integration_bee.qmd
          - text: "Integration Bee Practice"
            href: integration_practice.qmd
      - text: "Resources"
        menu:
          - text: "Learning Resources"
            href: resources.qmd
          - text: "Polya's Problem-Solving Method"
            href: polya.qmd
      - text: "Sponsors"
        href: sponsors.qmd
    right:
      - icon: github
        href: https://github.com/Zentannen/mathsoc
        aria-label: GitHub
  page-footer:
    background: "#002145"
    left: "© 2026 UCT Mathematics Society"
    center:
      - text: "Events"
        href: events.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Sponsors"
        href: sponsors.qmd
    right:
      - icon: envelope
        href: mailto:mathsoc@myuct.ac.za
        aria-label: Email
      - icon: github
        href: https://github.com/Zentannen/mathsoc
        aria-label: GitHub

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
